# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: platispete@gmail.com
copyright_name: Panagiotis Platis
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://platispete.github.io"
#twitter_username: SBootstrap
github_username:  platispete
facebook_username:  platoon0
email_username:  platispete@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-redirect-from, jekyll-seo-tag]
